# Generated by Django 5.2.3 on 2025-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('miniatura', models.ImageField(upload_to='portfolio/thumbnail/')),
                ('imagen_completa', models.ImageField(upload_to='portfolio/fullsize/')),
            ],
        ),
    ]
